#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT(KC_Q, KC_W, LT(8, KC_E), KC_R, KC_T, KC_Y, KC_U, KC_I, RALT_T(KC_O), KC_P, LT(5, KC_A), LT(4, KC_S), LCTL_T(KC_D), LT(6, KC_F), LALT_T(KC_G), KC_H, KC_J, KC_K, KC_L, RCTL_T(KC_SCLN), KC_Z, KC_X, LGUI_T(KC_C), KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_QUOT, LT(3, KC_ESC), LSFT_T(KC_SPC), RSFT_T(KC_SPC), RGUI_T(KC_BSPC)),
                                                              [1] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO, KC_NO),
                                                              [2] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO, KC_NO),
                                                              [3] = LAYOUT(KC_ESC, LGUI(KC_W), KC_NO, LGUI(KC_R), LGUI(KC_T), LAG(KC_I), SGUI(KC_P), KC_MINS, KC_LBRC, KC_RBRC, KC_TAB, LGUI(KC_S), KC_LGUI, KC_LALT, LSFT(KC_TAB), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_ENT, KC_LCTL, LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), LCA(KC_L), LGUI(KC_L), KC_GRV, KC_SLSH, KC_BSLS, KC_EQL, TO(0), KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [4] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LAG(KC_LEFT), LAG(KC_RGHT), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO, KC_NO),
                                                              [5] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_RGHT, KC_NO, KC_TRNS, KC_NO, KC_NO, RCS(KC_LALT), LALT(KC_RSFT), KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, TO(0), KC_NO, KC_TRNS, KC_TRNS),
                                                              [6] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PCMM, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_PDOT, KC_4, KC_5, KC_6, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, TO(0), KC_NO, KC_TRNS, KC_TRNS),
                                                              [7] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO, QK_BOOT),
                                                              [8] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_MACRO_4, QK_MACRO_3, QK_MACRO_2, QK_MACRO_1, QK_MACRO_0, QK_MACRO_17, QK_MACRO_16, KC_NO, KC_ESC, KC_NO, QK_MACRO_9, QK_MACRO_8, QK_MACRO_7, QK_MACRO_6, QK_MACRO_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_MACRO_14, QK_MACRO_13, QK_MACRO_12, QK_MACRO_11, QK_MACRO_10, KC_NO, KC_NO, KC_NO, LGUI(KC_P))};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

void matrix_init_user(void) {
    debug_enable   = true;
    debug_matrix   = true;
    debug_keyboard = true;
    debug_mouse    = true;
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        uprintf("Key pressed: %u\n", keycode);
    } else {
        uprintf("Key released: %u\n", keycode);
    }
    if (record->event.pressed) {
        switch (keycode) {
            case QK_MACRO_0:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_K) SS_UP(X_LCMD) SS_DOWN(X_LOPT) SS_TAP(X_F) SS_UP(X_LOPT));
                return false;
            case QK_MACRO_1:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_K) SS_UP(X_LCMD) SS_DOWN(X_LOPT) SS_TAP(X_T) SS_UP(X_LOPT));
                return false;
            case QK_MACRO_2:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_K) SS_UP(X_LCMD) SS_DOWN(X_LCMD) SS_TAP(X_I) SS_UP(X_LCMD));
                return false;
            case QK_MACRO_3:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_SEMICOLON) SS_UP(X_LCMD) SS_TAP(X_C));
                return false;
            case QK_MACRO_4:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_SEMICOLON) SS_UP(X_LCMD) SS_TAP(X_F));
                return false;
            case QK_MACRO_5:
                SEND_STRING(SS_DOWN(X_LSFT) SS_DOWN(X_RCTL) SS_TAP(X_R) SS_UP(X_RCTL) SS_UP(X_LSFT));
                return false;
            case QK_MACRO_6:
                SEND_STRING(SS_TAP(X_F2));
                return false;
            case QK_MACRO_7:
                SEND_STRING(SS_DOWN(X_LSFT) SS_TAP(X_F12) SS_UP(X_LSFT));
                return false;
            case QK_MACRO_8:
                SEND_STRING(SS_TAP(X_F12));
                return false;
            case QK_MACRO_9:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_K) SS_UP(X_LCMD) SS_TAP(X_X));
                return false;
            case QK_MACRO_10:
                SEND_STRING(SS_DOWN(X_LOPT) SS_DOWN(X_LCMD) SS_TAP(X_RIGHT) SS_UP(X_LCMD) SS_UP(X_LOPT));
                return false;
            case QK_MACRO_11:
                SEND_STRING(SS_DOWN(X_RCTL) SS_DOWN(X_RSFT) SS_TAP(X_G) SS_UP(X_RSFT) SS_UP(X_RCTL));
                return false;
            case QK_MACRO_12:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_E) SS_UP(X_LCMD) SS_TAP(X_F));
                return false;
            case QK_MACRO_13:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_E) SS_UP(X_LCMD) SS_TAP(X_W));
                return false;
            case QK_MACRO_14:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_E) SS_UP(X_LCMD) SS_TAP(X_G));
                return false;
            case QK_MACRO_15:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_K) SS_UP(X_LCMD) SS_TAP(X_O));
                return false;
            case QK_MACRO_16:
                SEND_STRING(SS_DOWN(X_LCMD) SS_TAP(X_E) SS_UP(X_LCMD) SS_DOWN(X_RSFT) SS_TAP(X_G) SS_UP(X_RSFT));
                return false;
            case QK_MACRO_17:
                SEND_STRING("thisisunsafe");
                return false;
        }
    }

    return true;
};

